.\" Manpage for diagram.
.\" Contact pekand@gmail.com to correct errors or typos.
.TH man 1 "01 Sep 2014" "1.0" "diagram man page"
.SH NAME
diagram \- create diagram
.SH SYNOPSIS
diagram [FILE]
.SH DESCRIPTION
Application for creating diagrams
.SH OPTIONS
The diagram does not take any options.
.SH BUGS
No known bugs.
.SH AUTHOR
Andrej Pekar (pekand@gmail.com)